
name: intel-compiler

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci_test_intel_icpx:
    runs-on: ubuntu-latest
    container: nickaein/nlohmann-json-ci:latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: cmake
        run: |
          source /opt/intel/oneapi/compiler/latest/env/vars.sh
          cmake -S . -B build -DJSON_CI=On
      - name: build
        run: |
          source /opt/intel/oneapi/compiler/latest/env/vars.sh
          cmake --build build --target ci_test_intel_icpx
